src/account/urls.py
from django.urls import path

from app.views import ListUsers
from account.views import Registration, Login, Logout


app_name = "account"

urlpatterns = [
    path("registration/", Registration.as_view(), name="registration"),
    path("login/", Login.as_view(), name="login"),
    path("logout/", Logout.as_view(), name="logout"),
    path("", ListUsers.as_view(),name="list-users"),
]

src/app/urls.py
from django.urls import path

from app.views import index, chat_room, video_chat, calling_status

app_name = "app"

urlpatterns = [
    path("", index, name="index"),
    path("chat/<str:chat_room>/", chat_room, name="chat-room"),
    path("video-chat/<str:video_chat_room>/", video_chat, name="video-chat"),
    path("calling-status/<str:calling_status_room>/<str:user_calling>/", calling_status, name="calling_status")
]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("account.urls")),
    path("app/", include("app.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/templates/calling_status.html
{% extends "index.html" %}
{% block content %}
{% load static %}
<link type="text/css" rel="stylesheet" href="{% static 'main.css' %}">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="center-button" style="position:relative;top:200px;">

    <h3 class="user-calling-text">video call from {{user_calling}}...</h3>
    <br>
    <button class="accept-call-button" id="answer">Answer</button>
    <button class="cancel-call-button" id="cancel">Cancel</button>

</div>

<audio src="http://localhost:8000/static/telephone-ring-04.mp3" autoplay></audio>

</body>

<script>
    var user = '{{user.username|safe}}'
    var callingStatusRoom = '{{calling_status_room|safe}}'
    var buttonAnswerCall = document.getElementById("answer")
    var buttonCancelCall = document.getElementById("cancel")


    const socket = new WebSocket('ws://' + window.location.host + '/ws/calling-status/'+callingStatusRoom+'/'+ user +"/");
    const websocket = new WebSocket('ws://' + window.location.host + '/ws/video-chat/'+callingStatusRoom +"/");


              socket.onopen = (event) => {
            console.log("WS status Opened")
            console.log(buttonAnswerCall.textContent,buttonCancelCall.textContent)
                    }

             socket.onmessage = (event) => {
            var data = JSON.parse(event.data);
                    }

             buttonCancelCall.addEventListener("click", function() {
            websocket.send(JSON.stringify({"event":"cancel-call"}))
            window.location.href = 'http://' + window.location.host + '/app/chat/'+ callingStatusRoom+"/";;
                    })

         buttonAnswerCall.addEventListener("click", function() {
            window.location.href = 'http://' + window.location.host + '/app/video-chat/'+ callingStatusRoom+"/";
                })


         setTimeout(function() {
              buttonCancelCall.click();
            }, 15000);

</script>
</html>

{% endblock %}

src/templates/chat_room.html
{% extends "index.html" %}
{% block content %}
<html lang="en" xmlns="http://www.w3.org/1999/html">
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
<head>


    <div id="div-call-status"></div>

{% if user.username == chat_instance.first_account.username or user.username == chat_instance.second_account.username %}
</head>

{% if user.username != chat_instance.first_account.username %}

<h2 class="title-chat-room">Chat room with {{chat_instance.first_account.username}}</h2>

{%else%}

<h2 class="title-chat-room">Chat room with {{chat_instance.second_account.username}}</h2>

{% endif %}



<div class="div-chat" id="myDiv" style="position:relative;">
    <div id="chat-content" class="chat-content"></div>
</div>



    <div class="center-button">
      <textarea type="text" id="textInput"></textarea>
        <button id="myButton" class="send-button" style="position:relative;top:-14px; right:-10px;">Send</button>
                <form class="form" method="POST">
              {% csrf_token %}
            <input type="hidden" value="{{chat_instance.pk}} {{user.username}}" name="video-call">
            <button id="video-call" type = 'submit' class="video-call-button" value ='Submit' style="position:relative;top:-47px; right:-250px;"></button>
            </form>
    </div>



<script>
var allMessages ={{all_messages|safe}}
var chatRoom = "{{ chat_instance.pk|safe }}";
var user = "{{ user.username|safe }}";
const divChat = document.getElementById("myDiv")

</script>
<script src="{% static 'text_messaging.js' %}"></script>

{% else %}

<div class="no-access-background">
<div class="no-access-text">
<h3>You have no access</h3>
    </div>
   </div>
{% endif %}


{% endblock %}
</html>

src/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Chat</title>
</head>
{% load static %}
<link type="text/css" rel="stylesheet" href="{% static 'main.css' %}">
<body>
<header>
  <div class="container">
    <div class="logo">Private chatting</div>
    <div class="user-info">
        {% if user.is_authenticated %}
      <span class="username" style="position:relative;right:15px;">{{user.username}}</span>


<a href="{% url 'account:list-users' %}" id="list-users" class="register-link" style="position:relative;right:3px;">List_Users</a>
<a href="{% url 'account:logout' %}" class="sign-in-link">Logout</a>



{% else %}
<a href="{% url 'account:list-users' %}" class="register-link", style="position:relative;right:30px;">Home</a>
<a href="{% url 'account:login' %}" class="sign-in-link">Sign in</a>
{% endif %}
    </div>
  </div>
</header>

</br></br>


{% block content %}

{% endblock %}


</body>

</html>

src/templates/list_users.html
{% extends "index.html" %}
{% block content %}
{% load static %}
<link type="text/css" rel="stylesheet" href="{% static 'main.css' %}">
<script>
            var user = "{{ user.username|safe }}";
        const socket = new WebSocket('ws://' + window.location.host + '/ws/list/1/');


</script>


<div class="div-call-status"></div>


<div class="center-button" style="position:relative; top:50px;">
{% for usr in object_list %}
{% if user.username != usr.username %}
   {% if usr.photo %}
   <img src={{usr.photo}} class="photo-list"><br>
    {% endif %}
<a class="username" style="position:relative;top:-2px;">{{usr.username}}</a><br>
    {% if user.is_authenticated %}
<form method="post">
    {% csrf_token %}
    <input type="hidden" value={{usr.username}} name="message">
    <button type="submit" class="send-message-button">Send Message</button>
</form>

    {% else %}

        <a href="{% url 'account:login' %}" class="send-message-button">Send Message</a>

    {% endif %}

    {% for unread_instance in all_unread %}
        {% if user.username == unread_instance.account.username and unread_instance.receiver_accounts.username == usr.username %}
        {% if unread_instance.count_unread|safe != "0" %}
    <p class="unread-messages">{{unread_instance.count_unread|safe}}</p>
            {% endif %}
            {% endif %}
    {% endfor %}
    <div id="myDiv">
    </div>

    <br><br><br><br>
{% endif %}



                <script>
        var user = "{{ user.username|safe }}";
        var divCallStatus = document.getElementById("div-call-status");

          socket.onopen = (event) => {

            console.log("WS Opened: ",event.data)

        }



        socket.onmessage = (event) => {


            var data = JSON.parse(event.data);
            if (data.calling) {console.log(data.calling);
            window.location.href = 'http://' + window.location.host + '/app/calling-status/'+ data.calling.room+"/"+data.calling["video-call-clicked"]+"/";
            }


            if (data.update) {
            if (user == data.update[0] || user == data.update[1]) {location.reload()}
                        }


        }



    </script>



{% endfor %}


{% endblock %}

src/templates/video_chat.html
{% extends "index.html" %}
{% block content %}
<html lang="en">
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
<head>
    <meta charset="UTF-8">


    Hello from video-chat room! {{video_chat_room.who_start_stream}}



{% if user.username == video_chat_room.first_account.username or user.username == video_chat_room.second_account.username %}
</head>

{% if user.username != video_chat_room.first_account.username %}

<h2 class="title-chat-room">Chat room with {{video_chat_room.first_account.username}}</h2>

{%else%}

<h2 class="title-chat-room">Chat room with {{video_chat_room.second_account.username}}</h2>

{% endif %}





    <div class="center-button">
            Hello from Div


<div id="videos">


     <div id="remote-videos" class>
         <video id="local-video" autoplay></video>
     </div>

  <br><br>
  <button id="start-button">Start Broadcast</button>
  <button id="stop-button">Stop Broadcast</button>
  <button id="turn-off-video">Turn off video</button>

  <br><br>


{% if user.username == video_chat_room.first_account.username %}
    <script>
        var secondUserVideo = "{{video_chat_room.second_account.video_on|safe}}"
    </script>
{% else %}
    <script>
        var secondUserVideo = "{{video_chat_room.first_account.video_on}}"
    </script>
{% endif %}

</div>
        </div>
<script>var whoStartStream = "{{ video_chat_room.who_start_stream|safe }}";</script>
<script>
var chatRoom = JSON.parse('{{ video_chat_room.pk|safe }}');
var user = "{{ user.username|safe }}";
</script>

<script type="text/javascript" src="{% static 'video-call.js' %}"></script>


{% else %}

<div class="no-access-background">
<div class="no-access-text">
<h3>You have no access</h3>
    </div>
   </div>
{% endif %}



{% endblock %}
</html>